baseURL = "/"
DefaultContentLanguage = "de"
languageCode = "de-at"
title = "blog.stousn.at"
theme = "terminal"
paginate = "5"

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "green"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2
  # set theme to full screen width
  fullWidthTheme = false
  # center theme with default width
  centerTheme = true
  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

[permalinks]
  posts = "/:filename/"

[languages]
  [languages.de]
    title = "blog.stousn.at"
    subtitle = "Blog"
    keywords = ""
    copyright = "&copy; Stefan Reip"
    menuMore = "Mehr anzeigen"
    readMore = "Weiterlesen"
    readOtherPosts = "Andere Posts"

    [languages.de.params.logo]
      logoText = "blog.stousn.at"
      logoHomeLink = "/"

    [languages.de.menu]
      [[languages.de.menu.main]]
        identifier = "home"
        name = "Home"
        url = "/"
        weight = 1

        [[languages.de.menu.main]]
        identifier = "stousn.at"
        name = "stousn.at"
        url = "https://stousn.at"
        weight = 3

        [[languages.de.menu.main]]
        identifier = "stousn.dev"
        name = "stousn.dev"
        url = "https://stousn.dev"
        weight = 4
#      [[languages.de.menu.main]]
 #       identifier = "showcase"
  #      name = "Showcase"
   #     url = "/showcase"